swagger: '2.0'
info:
  description: >-
    CodeRiver API 接口文档
  version: 1.0.0
  title: CodeRiver API Document
  # termsOfService: 'http://swagger.io/terms/'
  # contact:
  #   email: apiteam@swagger.io
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: home
    description: 首页相关的接口
  - name: user
    description: 用户服务相关接口

paths:
  /home/banners:
    get:
      tags:
        - home
      summary: 获取首页轮播图信息
      description: 将返回轮播图列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/BannerVO'

  /home/recommendProjects:
    get:
      tags:
        - home
      summary: 获取首页项目推荐列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/RecommendProjectVO'

  /home/recommendTeams:
    get:
      tags:
        - home
      summary: 获取首页团队推荐列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/RecommendTeamVO'

  /home/recommendHeroes:
    get:
      tags:
        - home
      summary: 获取首页英雄推荐列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/RecommendHeroVO'

  /user/login:
    post:
      tags:
        - user
      summary: 用户登录
      parameters:
        - name: username
          in: query
          description: 用户名
          required: true
          type: string
        - name: password
          in: query
          description: 密码
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            $ref: '#/definitions/User'

  /user/register:
    post:
      tags:
        - user
      summary: 用户注册
      parameters:
        - in: body
          name: body
          description: 用户填写的注册信息
          required: true
          schema:
            $ref: '#/definitions/RegisterForm'
      responses:
        '200':
          description: successful operation
          schema:
            type: string
            example:
              success
  /user/roles:
    get:
      tags:
        - user
      summary: 获取所有角色列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'

  /user/experiences:
    get:
      tags:
        - user
      summary: 获取经验列表
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Experience'


definitions:
  ResultVO:
    type: object
    description: 统一的返回格式
    properties:
      code:
        type: integer
        description: 返回码
      msg:
        type: string
        description: 返回信息
      data:
        type: object
        description: 返回的具体数据


  BannerVO:
    type: object
    properties:
      url:
        type: string
        description: 图片链接地址
      path:
        type: string
        description: 要跳转的页面路由地址

  RecommendProjectVO:
    type: object
    properties:
      name:
        type: string
        description: 团队名称
      introduce:
        type: string
        description: 团队介绍
      avatar:
        type: string
        description: 团队头像/logo
      pageView:
        type: integer
        format: int32
        description: 总浏览量
      heatNum:
        type: integer
        format: int32
        description: 热度值
      likeNum:
        type: integer
        format: int32
        description: 获得的点赞数

  RecommendTeamVO:
    type: object
    properties:
      teamName:
        type: string
        description: 队名
      recruitInfo:
        type: string
        description: 招募信息
      teamAvatar:
        type: string
        description: 团队logo
      introduce:
        type: string
        description: 团队介绍/一句话简介
      founderName:
        type: string
        description: 团队创始人名字
      founderAvatar:
        type: string
        description: 团队创始人头像

  RecommendHeroVO:
    type: object
    properties:
      title:
        type: string
        description: 分类标题
      list:
        type: array
        description: 该分类的具体数据
        items:
          $ref: '#/definitions/HomeHeroModel'

  HomeHeroModel:
    type: object
    properties:
      name:
        type: string
        description: 姓名
        example: 张三
      roleId:
        type: integer
        format: int32
        description: 角色码
        example:
          2
      roleName:
        type: string
        description: 角色名
        example:
          前端工程师
      avatar:
        type: string
        description: 头像
      introduce:
        type: string
        description: 个人简介

  RegisterForm:
    type: object
    properties:
      account:
        type: string
        description: 账户，手机号/邮箱
      password:
        type: string
        description: 密码
      username:
        type: string
        description: 昵称
      roleId:
        type: integer
        format: int32
        description: 角色id
      roleName:
        type: string
        description: 角色名
      experienceId:
        type: integer
        format: int32
        description: 经验id
      experienceName:
        type: string
        description: 经验名

  User:
    type: object
    properties:
      userId:
        type: string
        description: 用户id
      username:
        type: string
        description: 用户名
      sex:
        type: integer
        format: int32
        description: 性别
      token:
        type: string
        description: 登录凭证
      tel:
        type: string
        description: 电话
      email:
        type: string
        description: 邮箱
      avatar:
        type: string
        description: 头像
      roleId:
        type: integer
        format: int32
        description: 角色id
      roleName:
        type: string
        description: 角色名
      experienceId:
        type: integer
        format: int32
        description: 经验id
      experienceName:
        type: string
        description: 经验名
      city:
        type: string
        description: 城市
      influence:
        type: integer
        format: int32
        description: 影响力
      likeNum:
        type: integer
        format: int32
        description: 点赞数量

  Role:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 角色id
      name:
        type: string
        description: 角色名


  Experience:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 经验id
      name:
        type: string
        description: 经验名


externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'

 